from .AuthServiceController import router as AuthServiceController
from .StayServiceController import router as StayServiceController
from .BookingServiceController import router as BookingServiceController
from .PaymentServiceController import router as PaymentServiceController
from .InvoiceServiceController import router as InvoiceServiceController
from .RatingServiceController import router as RatingServiceController
